apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: docker.ellisbs.co.uk:5190/sonarqube:10.7.0-community
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_USERNAME
              value: sonar
            - name: SONAR_JDBC_PASSWORD
              value: sonar
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://192.168.0.76:5432/sonar
      volumes:
        - name: sonarqube-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
