apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  replicas: 2
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:community
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_USERNAME
              value: sonarcluster
            - name: SONAR_JDBC_PASSWORD
              value: sonarcluster
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://192.168.0.97:5432/sonarcluster
            - name: SONAR_JDBC_MAXACTIVE
              value: "5"
            - name: SONAR_JDBC_MAXIDLE
              value: "2"
            - name: SONAR_JDBC_MINIDLE
              value: "1"
            - name: SONAR_JDBC_MAXLIFETIME
              value: "600000"
      initContainers:
        - name: init-vm-max-map-count
          image: alpine:latest
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true  # Required to modify kernel parameters
      volumes:
        - name: sonarqube-data
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    app: sonarqube # Select pod with label app=sonarqube
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
